platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases-v2
    tag: latest
inputs:
- name: bosh-director
- name: bosh-compiled-releases
- name: release
- name: stemcell
outputs:
- name: compiled-release
run:
  path: bosh-compiled-releases/ci/tasks/compile-release/run.sh
