platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases-v2
    tag: latest
inputs:
- name: env
- name: compiled-release
- name: bosh-compiled-releases
outputs:
- name: analysis
run:
  path: sh
  args:
  - -ce
  - go run bosh-compiled-releases/ci/tasks/analyze-artifact-filesystem/run.go compiled-release/*.tgz > analysis/results.jsonl
