platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases-v2
    tag: latest
inputs:
- name: env
- name: compiled-release
- name: bosh-compiled-releases
outputs:
- name: analysis
run:
  path: go
  args:
  - run
  - bosh-compiled-releases/ci/tasks/analyze-artifact-checksum/run.go
  - compiled-release/*.tgz
