jobs:
- name: compile
  plan:
  - aggregate:
    - get: stemcell
      trigger: true
    - get: release
      trigger: true
    - get: bosh-compiled-releases
    - get: index
    - get: bosh-deployment
  - put: env
    params:
      acquire: true
  - do:
    - task: create-bosh-director
      file: bosh-compiled-releases/ci/tasks/create-bosh-director/task.yml
    - task: upload-stemcell
      file: bosh-compiled-releases/ci/tasks/upload-stemcell/task.yml
    - task: upload-release
      file: bosh-compiled-releases/ci/tasks/upload-release/task.yml
    - task: compile-release
      file: bosh-compiled-releases/ci/tasks/compile-release/task.yml
    - do:
      - task: publish-compiled-release
        file: bosh-compiled-releases/ci/tasks/publish-release/task.yml
        params:
          storage: ((index_storage))
          context: ((index_context))
      - put: index
    ensure:
      do:
      - task: destroy-bosh-director
        file: bosh-compiled-releases/ci/tasks/destroy-bosh-director/task.yml
      - put: env
        params:
          release: env
resources:
- name: bosh-deployment
  check_every: 24h
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
- name: bosh-compiled-releases
  check_every: 24h
  type: git
  source:
    uri: git@github.com:dpb587/bosh-compiled-releases-v2.git
    private_key: ((bcr_private_key))
- name: stemcell
  check_every: 24h
  type: metalink-repository
  source: ((stemcell_source))
- name: release
  check_every: 24h
  type: metalink-repository
  source: ((release_source))
- name: env
  check_every: 24h
  type: pool
  source:
    uri: git@github.com:dpb587/bosh-compiled-releases-envs.git
    branch: master
    private_key: ((envs_private_key))
    pool: dpb587-gcp
- name: index
  check_every: 24h
  type: git
  source:
    uri: git@github.com:dpb587/bosh-compiled-releases-index.git
    private_key: ((index_private_key))
resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
