jobs:
- name: compile
  plan:
  - aggregate:
    - get: stemcell
      trigger: true
    - get: release
      trigger: true
    - get: bosh-compiled-releases
    - get: index
    - get: bosh-deployment
  - put: env
    params:
      acquire: true
  - do:
    - task: create-bosh-director
      file: bosh-compiled-releases/ci/tasks/create-bosh-director/task.yml
    - task: upload-stemcell
      file: bosh-compiled-releases/ci/tasks/upload-stemcell/task.yml
    - task: upload-release
      file: bosh-compiled-releases/ci/tasks/upload-release/task.yml
    - task: compile-release
      file: bosh-compiled-releases/ci/tasks/compile-release/task.yml
    - do:
      - task: publish-compiled-release
        file: bosh-compiled-releases/ci/tasks/publish-compiled-release/task.yml
        params:
          storage: ((index_storage))
          context: ((index_context))
          release_version: ((release_version))
          s3_bucket: ((s3_bucket))
          s3_host: ((s3_host))
          s3_access_key: ((s3_access_key))
          s3_secret_key: ((s3_secret_key))
      - put: index
        params:
          repository: index
          rebase: true
    - parallel:
      - &teardown
      - do:
        - task: analyze-artifact-checksum
          file: bosh-compiled-releases/ci/tasks/analyze-artifact-checksum/task.yml
        - task: publish-analysis
          file: bosh-compiled-releases/ci/tasks/publish-analysis/task.yml
          params:
            storage: ((index_storage))
            analysis: artifact-checksum
            s3_bucket: ((s3_bucket))
            s3_host: ((s3_host))
            s3_access_key: ((s3_access_key))
            s3_secret_key: ((s3_secret_key))
        - put: index
          params:
            repository: index
            rebase: true
      - do:
        - task: analyze-artifact-filesystem
          file: bosh-compiled-releases/ci/tasks/analyze-artifact-filesystem/task.yml
        - task: publish-analysis
          file: bosh-compiled-releases/ci/tasks/publish-analysis/task.yml
          params:
            storage: ((index_storage))
            analysis: artifact-filesystem
            s3_bucket: ((s3_bucket))
            s3_host: ((s3_host))
            s3_access_key: ((s3_access_key))
            s3_secret_key: ((s3_secret_key))
        - put: index
          params:
            repository: index
            rebase: true
    on_failure: *teardown
      do:
      - task: destroy-bosh-director
        file: bosh-compiled-releases/ci/tasks/destroy-bosh-director/task.yml
      - put: env
        params:
          release: env
resources:
- name: bosh-deployment
  check_every: 24h
  type: git
  source:
    uri: https://github.com/cloudfoundry/bosh-deployment.git
- name: bosh-compiled-releases
  check_every: 24h
  type: git
  source:
    uri: git@github.com:dpb587/bosh-compiled-releases-v2.git
    private_key: ((bcr_private_key))
- name: stemcell
  check_every: 24h
  type: metalink-repository
  source: ((stemcell_source))
- name: release
  check_every: 24h
  type: metalink-repository
  source: ((release_source))
- name: env
  check_every: 24h
  type: pool
  source:
    uri: git@github.com:dpb587/bosh-compiled-releases-envs.git
    branch: master
    private_key: ((envs_private_key))
    pool: dpb587-gcp
- name: index
  check_every: 24h
  type: git
  source:
    branch: master
    uri: git@github.com:dpb587/bosh-compiled-releases-index.git
    private_key: ((index_private_key))
resource_types:
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
