jobs:
- name: build
  serial_groups:
  - version
  plan:
  - get: repo
    trigger: true
  - put: version
    params:
      pre: dev
  - task: build
    file: repo/ci/tasks/build/config.yml
  - put: repo-dev-artifacts
    params:
      files:
      - build/*
      version: version/version
    get_params:
      skip_download: true
- name: promote
  serial_groups:
  - version
  plan:
  - get: repo
    passed:
      - build
  - put: version
    params:
      bump: final
  - task: build
    file: repo/ci/tasks/build/config.yml
  - put: repo-final-artifacts
    params:
      files:
      - build/*
      version: version/version
  - task: build-release
    file: repo/ci/tasks/build-release/config.yml
    input_mapping:
      artifacts: repo-final-artifacts
  - put: repo
    params:
      annotate: release/title
      repository: repo
      only_tag: true
      tag: release/tag
  - put: github-release
    params:
      body: release/notes.md
      commitish: release/commit
      name: release/tag
      tag: release/tag
      globs:
      - release/blobs/*
    get_params:
      globs:
      - none
- name: bump-major
  serial_groups:
  - version
  plan:
  - put: version
    params:
      bump: major
- name: bump-minor
  serial_groups:
  - version
  plan:
  - put: version
    params:
      bump: minor
- name: bump-patch
  serial_groups:
  - version
  plan:
  - get: version
    trigger: true
    passed:
      - promote
  - put: version
    params:
      bump: patch

resources:
- name: repo
  type: git
  source: &repo
    uri: git@github.com:dpb587/boshua.git
    branch: master
    private_key: ((git_private_key))
- name: repo-dev-artifacts
  type: metalink-repository
  source:
    << : *release_artifacts
    uri: git+ssh://git@github.com:dpb587/boshua.git//boshua-dev#artifacts
- name: repo-final-artifacts
  type: metalink-repository
  source:
    << : *release_artifacts
    uri: git+ssh://git@github.com:dpb587/boshua.git//boshua-final#artifacts
- name: "repo-artifacts"
  type: "git"
  source:
    uri: git@github.com:dpb587/boshua.git
    branch: artifacts
    private_key: ((git_private_key))
- name: github-release
  type: github-release
  source:
    access_token: ((repo_github_token))
    repository: boshua
    user: dpb587
- name: "version"
  type: "semver"
  source:
    <<: *repo
    driver: git
    branch: ci-state
    file: version/master
resource_types:
- name: github-status
  type: docker-image
  source:
    repository: dpb587/github-status-resource
    tag: master
- name: metalink-repository
  type: docker-image
  source:
    repository: dpb587/metalink-repository-resource
shared:
  release_artifacts: &release_artifacts
    mirror_files:
    - destination: s3://s3-external-1.amazonaws.com/dpb587-boshua-us-east-1/artifacts/v{{.Version}}/{{.SHA1}}
      env:
        AWS_ACCESS_KEY_ID: ((artifacts_s3_access_key))
        AWS_SECRET_ACCESS_KEY: ((artifacts_s3_secret_key))
    options:
      private_key: ((git_private_key))
