#!/bin/bash

set -eu

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

exec fly -t "$FLY_TARGET" set-pipeline \
  -p boshua \
  -c ci/pipeline.yml \
  -l <( terraform output --json | jq 'to_entries | map({key, "value": .value.value}) | from_entries' ) \
  -l <( lpass show --sync=now --notes "Secure Notes/github.com/dpb587/boshua/ci/secrets.yml" )
