platform: linux
image_resource:
  type: docker-image
  source:
    repository: dpb587/bosh-compiled-releases-v2
    tag: latest
inputs:
- name: artifact
- name: bosh-compiled-releases
outputs:
- name: analysis
run:
  path: bash
  args:
  - -c
  - |
    exec > analysis/results.jsonl
    boshua analysis --analyzer=$analyzer generate artifact/*.tgz
params:
  analyzer: ~
